### ISSUE TITLE
Suggestion for an Upgrade

### ISSUE THREAD

**Issue by Aeonsteel** [LegoMaster3650/ItemUpgrader#2]
Carved Pumpkin upgrade for a Helmet should make it so Endermen don't get angry if you look at them.

**Comment by LegoMaster3650** [comment]
That's actually an interesting suggestion! I'll see what I can do.

**Comment by Aeonsteel** [comment]
Tinted Glass might also work, like mirrored shades so they can't tell where you're looking

**Comment by LegoMaster3650** [comment]
Added in commit f498c3e. Thanks for the suggestion!
