### ISSUE TITLE
I dont know what happening

### ISSUE THREAD

**Issue by luigodly** [LegoMaster3650/ItemUpgrader#3]
Made a custom modpack, with this mod, it gives me no errors when starting up, but when i try to find the items in game and in the menus or try crafting the upgrades nothing shows.

Here is my latest log:
[latest.log](https://github.com/LegoMaster3650/ItemUpgrader/files/10442521/latest.log)

please help 
and love the concept of the mod just waiting to actually play it

**Comment by LegoMaster3650** [comment]
I've reviewed the log, and it actually seems like the mod is loading fine and JEI is even reading recipes... Try clicking on the hammer in the smithing table (like you would the arrow to view recipes) and tell me if you see anything.

**Comment by luigodly** [comment]
Yeah that worked I was just being dumb, I thought it wasnt loading because it wouldnt show in the jei menu, but it was there. Thank you for your help, 

Cant wait when this mod is fully complete
