### ISSUE TITLE
Upgrades not working on Server

### ISSUE THREAD

**Issue by Talan67** [LegoMaster3650/ItemUpgrader#4]
Log: https://paste.ee/p/nZFLF

Forge Version 43.2.0
Item Upgrader 1.0.1

**Comment by LegoMaster3650** [comment]
Need a bit more info to see what the issue is. Which upgrades aren't working, and how so? If you just can't find the recipes, the JEI shortcut is clicking on the hammer in the smithing table. If that's not the case, tell me what you're trying and what isn't working about it. Thanks!

**Comment by Talan67** [comment]
an item with the echoing upgrade is not kept upon death, I tested it on both my server and singleplayer, it was working fine in singleplayer but not at all on the server

**Comment by Talan67** [comment]
im hoping on minecraft right now, going to check all upgrades make sure nothing else is wrong

**Comment by Talan67** [comment]
It is only the Echoing upgrade

**Comment by LegoMaster3650** [comment]
Just tested it, seems fine to me. Does the upgrade have charges left? That upgrade has a limited number of uses (it can be refilled or stacked using more echo shards) for balance, although you can change the amount of charges per echo shard in the `itemupgrader_content-common` config under `functionality.soulboundCharges` (or disabled entirely by setting it to -1)
